--- # Webservers lab
- hosts: webservers
  become: yes
  vars_files:
    - /home/ansible/confidential
  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: latest
      notify: httpd_bounce
      tags:
        - base-install
    - name: Configure virtual host
      template:
        src: /home/ansible/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
      notify: httpd_bounce
      tags:
        - vhost
    - name: Configure website authentication
      template:
        src: /home/ansible/htpasswd.j2
        dest: /etc/httpd/conf/htpasswd
      notify: httpd_bounce
      tags:
        - vhost
    - name: Run data job
      command: /opt/data-job.sh
      async: 600
      poll: 0
      tags:
        - data-job
  handlers:
    - name: Restart and enable Apache
      service:
        name: httpd
        state: restarted
        enabled: yes
      listen: httpd_bounce