--- # Ansible conditional example
- hosts: nodes
  vars:
    target_file: /home/ansible/hostname
  tasks:
    - name: Get file information
      stat:
        path: "{{ target_file }}"
      register: hostname
    - name: Rename hostname file if found    
      command: mv "{{ target_file }}" /home/ansible/net-info
      when: hostname.stat.exists
