---
- hosts: centos
  tasks:
    - name: create working directory
      file:
        name: "{{ working_dir }}"
        state: directory
    - name: write service list
      lineinfile:
        path: "{{ working_dir }}/services.txt"
        create: yes      
        line: "{{ service_list }}"
    - name: view share property
      command: ls -la "{{ test_paths['device'] }}"
      register: cmd_output
    - name: write command module output to file
      copy:
        content: "{{ cmd_output }}"
        dest: "{{ working_dir }}/cmd_output.txt"        
